#!/bin/bash

pip install nbconvert[webpdf]
pip install -U notebook-as-pdf
pyppeteer-install

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"

test -e test.png && rm test.png

# install JupyterLab extension
jupyter labextension install @jupyterlab/latex
